export const SHOP = {
  nameTh: 'ชาบูอร่อยจัง',
  nameEn: 'Shabu Aroi Jang',
  phone: '06-1564-0529',
  addressTh: '125/3 ม.5 ต.สามควายเผือก อ.เมือง จ.นครปฐม 73000',
  priceAdult: 299,
  priceChild: 149,
  freeHeightCm: 90,
  childMaxHeightCm: 120,
  diningMinutes: 120,
  openTime: '11:00',
  closeTime: '22:00',
  promptpay: '06-1564-0529',
}

export const TABLES = [
  ['A01',2],['A02',2],['A03',4],['A04',4],['A05',4],['A06',4],['A07',4],['A08',4],
  ['A09',6],['A10',6],['B01',6],['B02',6],['B03',8],['B04',8],['B05',10],
].map(([code,seats], index) => ({ code, seats, sort_order:index+1 }))

export const MENU = [
  ['หมู','หมูสามชั้น','Pork Belly','🥓'],
  ['หมู','หมูสันคอ','Pork Collar','🥩'],
  ['หมู','หมูนุ่ม','Tender Pork','🥩'],
  ['หมู','หมูหมักงา','Sesame Pork','🥩'],
  ['หมู','หมูพริกไทยดำ','Black Pepper Pork','🥩'],
  ['หมู','เบคอน','Bacon','🥓'],
  ['หมู','หมูเด้ง','Pork Balls','🍖'],
  ['หมู','หมูพันเห็ดเข็มทอง','Enoki Pork Roll','🍄'],
  ['หมู','ตับหมู','Pork Liver','🥩'],
  ['เนื้อ','เนื้อสไลซ์','Beef Slice','🥩'],
  ['เนื้อ','เนื้อใบพาย','Chuck Tender','🥩'],
  ['เนื้อ','เนื้อริบอาย','Ribeye','🥩'],
  ['เนื้อ','เนื้อติดมัน','Marbled Beef','🥩'],
  ['เนื้อ','เนื้อหมักงา','Sesame Beef','🥩'],
  ['เนื้อ','เนื้อพริกไทยดำ','Black Pepper Beef','🥩'],
  ['ไก่','ไก่นุ่ม','Tender Chicken','🍗'],
  ['ไก่','ไก่หมักงา','Sesame Chicken','🍗'],
  ['ไก่','ไก่พริกไทยดำ','Black Pepper Chicken','🍗'],
  ['ซีฟู้ด','กุ้ง','Shrimp','🦐'],
  ['ซีฟู้ด','ปลาหมึก','Squid','🦑'],
  ['ซีฟู้ด','ปลาดอลลี่','Dory Fish','🐟'],
  ['ซีฟู้ด','หอยแมลงภู่','Mussels','🦪'],
  ['ซีฟู้ด','ปูอัด','Crab Stick','🦀'],
  ['ซีฟู้ด','เต้าหู้ปลา','Fish Tofu','🍢'],
  ['ซีฟู้ด','หมึกกรอบ','Crispy Squid','🦑'],
  ['ผัก','ผักกาดขาว','Chinese Cabbage','🥬'],
  ['ผัก','ผักบุ้ง','Morning Glory','🥬'],
  ['ผัก','กะหล่ำปลี','Cabbage','🥬'],
  ['ผัก','ข้าวโพด','Corn','🌽'],
  ['ผัก','ข้าวโพดอ่อน','Baby Corn','🌽'],
  ['ผัก','ฟักทอง','Pumpkin','🎃'],
  ['ผัก','แครอท','Carrot','🥕'],
  ['ผัก','หัวไชเท้า','Daikon','🥕'],
  ['เห็ด','เห็ดเข็มทอง','Enoki','🍄'],
  ['เห็ด','เห็ดออรินจิ','King Oyster Mushroom','🍄'],
  ['เห็ด','เห็ดชิเมจิ','Shimeji','🍄'],
  ['เห็ด','เห็ดหอม','Shiitake','🍄'],
  ['เส้น','วุ้นเส้น','Glass Noodles','🍜'],
  ['เส้น','บะหมี่หยก','Jade Noodles','🍜'],
  ['เส้น','มาม่า','Instant Noodles','🍜'],
  ['เส้น','อุด้ง','Udon','🍜'],
  ['ของชาบู','ลูกชิ้นหมู','Pork Ball','🍢'],
  ['ของชาบู','ลูกชิ้นเนื้อ','Beef Ball','🍢'],
  ['ของชาบู','ลูกชิ้นปลา','Fish Ball','🍢'],
  ['ของชาบู','ชีสบอล','Cheese Ball','🧀'],
  ['ของชาบู','ฟองเต้าหู้','Bean Curd Sheet','🍢'],
  ['ของชาบู','เต้าหู้ไข่','Egg Tofu','🍳'],
  ['ของชาบู','เกี๊ยวกุ้ง','Shrimp Wonton','🥟'],
  ['ของชาบู','ไส้กรอกชีส','Cheese Sausage','🌭'],
  ['ของทานเล่น','เฟรนช์ฟรายส์','French Fries','🍟'],
  ['ของทานเล่น','นักเก็ตไก่','Chicken Nuggets','🍗'],
  ['ของทานเล่น','ไก่ทอด','Fried Chicken','🍗'],
  ['ของทานเล่น','เกี๊ยวทอด','Fried Wonton','🥟'],
  ['ของทานเล่น','ข้าวผัดกระเทียม','Garlic Rice','🍚'],
  ['ของทานเล่น','ข้าวสวย','Steamed Rice','🍚'],
  ['น้ำซุป','น้ำดำญี่ปุ่น','Japanese Black Soup','🍲'],
  ['น้ำซุป','น้ำใส','Clear Soup','🍲'],
  ['น้ำซุป','ต้มยำ','Tom Yum','🌶️'],
  ['น้ำซุป','หม่าล่า','Mala','🔥'],
  ['น้ำซุป','สุกี้ยากี้','Sukiyaki','🍲'],
  ['น้ำจิ้ม','น้ำจิ้มสุกี้','Suki Sauce','🥣'],
  ['น้ำจิ้ม','น้ำจิ้มซีฟู้ด','Seafood Sauce','🌶️'],
  ['น้ำจิ้ม','น้ำจิ้มงา','Sesame Sauce','🥣'],
  ['น้ำจิ้ม','พอนสึ','Ponzu','🥣'],
  ['เครื่องดื่ม','น้ำเปล่า','Water','💧'],
  ['เครื่องดื่ม','โค้ก','Coke','🥤'],
  ['เครื่องดื่ม','โค้กซีโร่','Coke Zero','🥤'],
  ['เครื่องดื่ม','สไปรท์','Sprite','🥤'],
  ['เครื่องดื่ม','ชาเขียว','Green Tea','🍵'],
  ['เครื่องดื่ม','ชามะนาว','Lemon Tea','🍋'],
  ['ของหวาน','ไอศกรีมวานิลลา','Vanilla Ice Cream','🍨'],
  ['ของหวาน','ไอศกรีมช็อกโกแลต','Chocolate Ice Cream','🍨'],
  ['ของหวาน','ไอศกรีมสตรอว์เบอร์รี','Strawberry Ice Cream','🍓'],
  ['ของหวาน','ไอศกรีมชาเขียว','Matcha Ice Cream','🍵'],
  ['ของหวาน','เฉาก๊วย','Grass Jelly','🍮'],
  ['ของหวาน','ผลไม้ตามฤดูกาล','Seasonal Fruit','🍉'],
].map(([category,name_th,name_en,emoji],index)=>({
  id:`m${index+1}`, category, name_th, name_en, emoji, is_available:true, sort_order:index+1
}))

export const ORDER_FLOW = ['pending','accepted','preparing','ready','served']
export const ORDER_LABEL = {
  pending:'รอรับ', accepted:'รับแล้ว', preparing:'กำลังเตรียม', ready:'พร้อมเสิร์ฟ', served:'เสิร์ฟแล้ว', cancelled:'ยกเลิก'
}
export const TABLE_LABEL = {
  available:'ว่าง', reserved:'จองแล้ว', occupied:'กำลังใช้บริการ', service:'เรียกพนักงาน',
  billing:'รอเช็คบิล', cleaning:'ทำความสะอาด', disabled:'ปิดใช้งาน'
}
