import { useEffect, useState } from 'react'
import { QRCodeCanvas } from 'qrcode.react'
import {
  detachSessionTable, listActiveSessions, listTables, markTableReady, mergeSessionTable, moveTableSession,
  openWalkin, regenerateSessionQr, subscribeAll, updateSessionGuests
} from '../lib/api'

function Head(){return <div className="admin-head"><div><span className="eyebrow">TABLE OPERATIONS</span><h1>จัดการโต๊ะ / Walk-in</h1><p>ย้าย รวม แยกโต๊ะ ปรับจำนวนคน และจัดการ QR</p></div></div>}
function Modal({title,onClose,children}){return <div className="modal-backdrop" onClick={onClose}><div className="pro-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={onClose}>×</button><h2>{title}</h2>{children}</div></div>}

export default function TablesAdminPro(){
  const [tables,setTables]=useState([]),[sessions,setSessions]=useState([]),[walkin,setWalkin]=useState(null),[move,setMove]=useState(null),[qrSession,setQrSession]=useState(null),[combine,setCombine]=useState(null),[guestEdit,setGuestEdit]=useState(null)
  const [counts,setCounts]=useState({adult:2,child:0,free:0})
  async function load(){const [t,s]=await Promise.all([listTables(),listActiveSessions()]);setTables(t);setSessions(s)}
  useEffect(()=>{load();return subscribeAll(load)},[])
  async function open(){try{const created=await openWalkin(walkin.id,counts.adult,counts.child,counts.free);setWalkin(null);setQrSession(created);setCounts({adult:2,child:0,free:0});await load()}catch(e){alert(e.message)}}
  async function moveNow(id){try{await moveTableSession(move.id,id);setMove(null);await load()}catch(e){alert(e.message)}}
  async function mergeNow(id){try{await mergeSessionTable(combine.id,id);setCombine(null);await load()}catch(e){alert(e.message)}}
  async function saveGuests(){try{await updateSessionGuests(guestEdit.id,guestEdit.adult_count,guestEdit.child_count,guestEdit.free_child_count);setGuestEdit(null);await load()}catch(e){alert(e.message)}}
  async function regen(){if(!confirm('สร้าง QR ใหม่? QR เดิมจะใช้ไม่ได้ทันที'))return;const x=await regenerateSessionQr(qrSession.id);setQrSession({...qrSession,token:x.token});await load()}
  function downloadQr(){const canvas=document.getElementById('table-qr-canvas');if(!canvas)return;const a=document.createElement('a');a.href=canvas.toDataURL('image/png');a.download='table-'+(qrSession?.table_code||'QR')+'.png';a.click()}
  const activeByTable=new Map();sessions.forEach(s=>(s.linked_tables?.length?s.linked_tables:[{table_id:s.table_id}]).forEach(l=>activeByTable.set(l.table_id,s)))
  const qrUrl=qrSession?.token?window.location.origin+'/shabu-aroi-jang/table/'+qrSession.token:''
  return <><Head/><div className="floor-grid">{tables.map(t=>{const s=activeByTable.get(t.id);return <article className={'table-tile '+t.status} key={t.id}><div className="table-icon">🍲</div><h2>{t.code}</h2><p>{t.seats} ที่นั่ง</p><span className={'status status-'+t.status}>{t.status}</span>{s&&<small>{s.guest_count} คน • {s.status}</small>}<div className="table-actions">{t.status==='available'&&<button className="mini-btn ok" onClick={()=>setWalkin(t)}>+ Walk-in</button>}{s&&<button className="mini-btn qr" onClick={()=>setQrSession(s)}>QR</button>}{s&&<button className="mini-btn" onClick={()=>setGuestEdit({...s,adult_count:s.adult_count||s.guest_count||0,child_count:s.child_count||0,free_child_count:s.free_child_count||0})}>จำนวนคน</button>}{s&&<button className="mini-btn" onClick={()=>setMove(s)}>ย้าย</button>}{s&&<button className="mini-btn" onClick={()=>setCombine(s)}>รวมโต๊ะ</button>}{t.status==='cleaning'&&<button className="mini-btn ok" onClick={async()=>{await markTableReady(t.id);load()}}>พร้อมใช้งาน</button>}</div>{s?.linked_tables?.filter(l=>!l.is_primary).map(l=><button key={l.table_id} className="linked-table-chip" onClick={async()=>{if(confirm('แยก '+l.code+' ออกจาก Session?')){await detachSessionTable(s.id,l.table_id);load()}}}>แยก {l.code} ×</button>)}</article>})}</div>
  {walkin&&<Modal title={'เปิดโต๊ะ '+walkin.code} onClose={()=>setWalkin(null)}><div className="pro-form"><label>ผู้ใหญ่<input type="number" min="0" value={counts.adult} onChange={e=>setCounts(c=>({...c,adult:Number(e.target.value)}))}/></label><label>เด็ก 90–120 ซม.<input type="number" min="0" value={counts.child} onChange={e=>setCounts(c=>({...c,child:Number(e.target.value)}))}/></label><label>เด็กฟรี<input type="number" min="0" value={counts.free} onChange={e=>setCounts(c=>({...c,free:Number(e.target.value)}))}/></label><button className="btn primary span-2" onClick={open}>เปิดโต๊ะและสร้าง QR</button></div></Modal>}
  {move&&<Modal title={'ย้ายโต๊ะ '+move.table_code} onClose={()=>setMove(null)}><div className="simple-list">{tables.filter(t=>t.status==='available'&&t.seats>=move.guest_count).map(t=><div key={t.id}><span><b>{t.code}</b><small>{t.seats} ที่นั่ง</small></span><button className="mini-btn ok" onClick={()=>moveNow(t.id)}>ย้ายมาที่นี่</button></div>)}</div></Modal>}
  {combine&&<Modal title={'รวมโต๊ะกับ '+combine.table_code} onClose={()=>setCombine(null)}><div className="simple-list">{tables.filter(t=>t.status==='available').map(t=><div key={t.id}><span><b>{t.code}</b><small>{t.seats} ที่นั่ง</small></span><button className="mini-btn ok" onClick={()=>mergeNow(t.id)}>รวมโต๊ะ</button></div>)}</div></Modal>}
  {guestEdit&&<Modal title={'ปรับจำนวนคน '+guestEdit.table_code} onClose={()=>setGuestEdit(null)}><div className="pro-form"><label>ผู้ใหญ่<input type="number" min="0" value={guestEdit.adult_count} onChange={e=>setGuestEdit(x=>({...x,adult_count:Number(e.target.value)}))}/></label><label>เด็ก<input type="number" min="0" value={guestEdit.child_count} onChange={e=>setGuestEdit(x=>({...x,child_count:Number(e.target.value)}))}/></label><label>เด็กฟรี<input type="number" min="0" value={guestEdit.free_child_count} onChange={e=>setGuestEdit(x=>({...x,free_child_count:Number(e.target.value)}))}/></label><button className="btn primary span-2" onClick={saveGuests}>บันทึก</button></div></Modal>}
  {qrSession&&<Modal title={'QR โต๊ะ '+(qrSession.table_code||'-')} onClose={()=>setQrSession(null)}><div className="admin-qr-box"><QRCodeCanvas id="table-qr-canvas" value={qrUrl} size={250}/></div><div className="qr-modal-actions"><a className="btn dark" href={qrUrl} target="_blank" rel="noreferrer">เปิดหน้าโต๊ะ</a><button className="btn ghost" onClick={()=>navigator.clipboard?.writeText(qrUrl)}>คัดลอก</button><button className="btn ghost" onClick={downloadQr}>ดาวน์โหลด PNG</button><button className="btn ghost" onClick={regen}>Regenerate</button><button className="btn primary" onClick={()=>window.print()}>พิมพ์</button></div></Modal>}</>
}
